name: Inject DB Info

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set and debug env variables
        env:
          DB_PASSWORD: ${{ secrets.database_login_info }}
          DB_USERNAME: ${{ secrets.database_login_username }}
        run: |
          echo "DB_USERNAME is set: ${DB_USERNAME}"
          echo "DB_PASSWORD is set: ${DB_PASSWORD}"
