name: Inject DB Info

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set and debug env variables
        env:
          DB_USER: ${{ secrets.DB_USERNAME }}
          DB_PW: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "DB_USER is set: ${#DB_USER}"
          echo "DB_PW is set: ${#DB_PW}"

      - name: Build with Maven
        workingDirectory: ./backend/task-manager
        run: mvn clean install
