name: Inject DB Password

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Build with Maven
        env:
          DB_PASSWORD: ${{ secrets.database_login_info }}
          DB_USERNAME: ${{secrets.database_login_username}}
        run: mvn clean package -Dspring.profiles.active=prod