name: Inject DB Info

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set and debug env variables
        env:
          DB_USER: ${{ secrets.DB_USERNAME }}
          DB_PW: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "DB_USER is set: ${#DB_USER}"
          echo "DB_PW is set: ${#DB_PW}"

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        working-directory: ./backend/task-manager
        run: mvn clean install
