#This is a workflow to build a java project
name: JavaCI

on:
  push:
    branches:
      - main
      - Github-Secrets-Injecting

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21
          cache: 'maven'
      - name: Build with Maven
        run: mvn -D DBUSERNAMEFROMYML=${{ secrets.database_login_username }} -D DBPASSWORDFROMYML=${{ secrets.database_login_info }} clean package --file backend/task-manager/pom.xml
        
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging


 
