#This is a workflow to build a java project
name: JavaCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - env:
        databaseLoginUsername: ${{ secrets.database_login_username }}
        databaseLoginInfo: ${{secrets.database_login_info}}
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: 21
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file backend/task-manager/pom.xml
