#This is a workflow to build a java project
name: JavaCI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B -D DBUSERNAMEFROMYML=${{ secrets.database_login_username }} -D DBPASSWORDFROMYML=${{ secrets.database_login_info }} package --file backend/task-manager/pom.xml


 
